project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: about.ipynb
        text: About

format:
  html:
    theme: flatly
    toc: true